// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: meta.proto

package proto_gen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// META //
type RequestMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	//  bool mine = 2;
	UserId         int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Description    string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	TopicId        int64    `protobuf:"varint,4,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	FileId         int64    `protobuf:"varint,5,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	SequenceId     int64    `protobuf:"varint,6,opt,name=sequence_id,json=sequenceId,proto3" json:"sequence_id,omitempty"`
	Paging         *Paging  `protobuf:"bytes,7,opt,name=paging,proto3" json:"paging,omitempty"`
	File           *File    `protobuf:"bytes,8,opt,name=file,proto3" json:"file,omitempty"`
	Profile        *Profile `protobuf:"bytes,9,opt,name=profile,proto3" json:"profile,omitempty"`
	NotificationId int64    `protobuf:"varint,10,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
}

func (x *RequestMeta) Reset() {
	*x = RequestMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMeta) ProtoMessage() {}

func (x *RequestMeta) ProtoReflect() protoreflect.Message {
	mi := &file_meta_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMeta.ProtoReflect.Descriptor instead.
func (*RequestMeta) Descriptor() ([]byte, []int) {
	return file_meta_proto_rawDescGZIP(), []int{0}
}

func (x *RequestMeta) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *RequestMeta) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RequestMeta) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RequestMeta) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *RequestMeta) GetFileId() int64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

func (x *RequestMeta) GetSequenceId() int64 {
	if x != nil {
		return x.SequenceId
	}
	return 0
}

func (x *RequestMeta) GetPaging() *Paging {
	if x != nil {
		return x.Paging
	}
	return nil
}

func (x *RequestMeta) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *RequestMeta) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *RequestMeta) GetNotificationId() int64 {
	if x != nil {
		return x.NotificationId
	}
	return 0
}

type ResponseMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header            *Header         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Topic             []*Topic        `protobuf:"bytes,2,rep,name=topic,proto3" json:"topic,omitempty"`
	Messages          []*Message      `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	Users             []*User         `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty"`
	Profiles          []*Profile      `protobuf:"bytes,5,rep,name=profiles,proto3" json:"profiles,omitempty"`
	Profile           *Profile        `protobuf:"bytes,6,opt,name=profile,proto3" json:"profile,omitempty"`
	File              *File           `protobuf:"bytes,7,opt,name=file,proto3" json:"file,omitempty"`
	Notifications     []*Notification `protobuf:"bytes,8,rep,name=notifications,proto3" json:"notifications,omitempty"`
	Result            *Result         `protobuf:"bytes,9,opt,name=result,proto3" json:"result,omitempty"`
	UserCount         int64           `protobuf:"varint,10,opt,name=user_count,json=userCount,proto3" json:"user_count,omitempty"`
	TopicCount        int64           `protobuf:"varint,11,opt,name=topic_count,json=topicCount,proto3" json:"topic_count,omitempty"`
	MessageCount      int64           `protobuf:"varint,12,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	UserMaxId         int64           `protobuf:"varint,133,opt,name=user_max_id,json=userMaxId,proto3" json:"user_max_id,omitempty"`
	TopicMaxId        int64           `protobuf:"varint,14,opt,name=topic_max_id,json=topicMaxId,proto3" json:"topic_max_id,omitempty"`
	MessageMaxId      int64           `protobuf:"varint,15,opt,name=message_max_id,json=messageMaxId,proto3" json:"message_max_id,omitempty"`
	NotificationMaxId int64           `protobuf:"varint,16,opt,name=notification_max_id,json=notificationMaxId,proto3" json:"notification_max_id,omitempty"`
	Notification      *Notification   `protobuf:"bytes,17,opt,name=notification,proto3" json:"notification,omitempty"`
	TopicIds          []int64         `protobuf:"varint,18,rep,packed,name=topic_ids,json=topicIds,proto3" json:"topic_ids,omitempty"`
}

func (x *ResponseMeta) Reset() {
	*x = ResponseMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseMeta) ProtoMessage() {}

func (x *ResponseMeta) ProtoReflect() protoreflect.Message {
	mi := &file_meta_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseMeta.ProtoReflect.Descriptor instead.
func (*ResponseMeta) Descriptor() ([]byte, []int) {
	return file_meta_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseMeta) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ResponseMeta) GetTopic() []*Topic {
	if x != nil {
		return x.Topic
	}
	return nil
}

func (x *ResponseMeta) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ResponseMeta) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ResponseMeta) GetProfiles() []*Profile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

func (x *ResponseMeta) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *ResponseMeta) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *ResponseMeta) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

func (x *ResponseMeta) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ResponseMeta) GetUserCount() int64 {
	if x != nil {
		return x.UserCount
	}
	return 0
}

func (x *ResponseMeta) GetTopicCount() int64 {
	if x != nil {
		return x.TopicCount
	}
	return 0
}

func (x *ResponseMeta) GetMessageCount() int64 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *ResponseMeta) GetUserMaxId() int64 {
	if x != nil {
		return x.UserMaxId
	}
	return 0
}

func (x *ResponseMeta) GetTopicMaxId() int64 {
	if x != nil {
		return x.TopicMaxId
	}
	return 0
}

func (x *ResponseMeta) GetMessageMaxId() int64 {
	if x != nil {
		return x.MessageMaxId
	}
	return 0
}

func (x *ResponseMeta) GetNotificationMaxId() int64 {
	if x != nil {
		return x.NotificationMaxId
	}
	return 0
}

func (x *ResponseMeta) GetNotification() *Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

func (x *ResponseMeta) GetTopicIds() []int64 {
	if x != nil {
		return x.TopicIds
	}
	return nil
}

var File_meta_proto protoreflect.FileDescriptor

var file_meta_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x1a, 0x0b, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xef, 0x02, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x4d, 0x65, 0x74, 0x61, 0x12, 0x29, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e,
	0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x6f,
	0x70, 0x69, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x74, 0x6f,
	0x70, 0x69, 0x63, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1f,
	0x0a, 0x0b, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12,
	0x29, 0x0a, 0x06, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x2e, 0x50, 0x61, 0x67, 0x69,
	0x6e, 0x67, 0x52, 0x06, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x12, 0x23, 0x0a, 0x04, 0x66, 0x69,
	0x6c, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x5f, 0x67, 0x65, 0x6e, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x12,
	0x2c, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x2e, 0x50, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x27, 0x0a,
	0x0f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0xfd, 0x05, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x29, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f,
	0x67, 0x65, 0x6e, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x12, 0x26, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x2e, 0x54, 0x6f,
	0x70, 0x69, 0x63, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x2e, 0x0a, 0x08, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x05, 0x75, 0x73,
	0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72,
	0x73, 0x12, 0x2e, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x2e,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x73, 0x12, 0x2c, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x2e, 0x50,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12,
	0x23, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x04,
	0x66, 0x69, 0x6c, 0x65, 0x12, 0x3d, 0x0a, 0x0d, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x29, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x2e,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1f, 0x0a,
	0x0b, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x23,
	0x0a, 0x0d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6d, 0x61, 0x78, 0x5f,
	0x69, 0x64, 0x18, 0x85, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x4d,
	0x61, 0x78, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0c, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x5f, 0x6d, 0x61,
	0x78, 0x5f, 0x69, 0x64, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x74, 0x6f, 0x70, 0x69,
	0x63, 0x4d, 0x61, 0x78, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x5f, 0x6d, 0x61, 0x78, 0x5f, 0x69, 0x64, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4d, 0x61, 0x78, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x13,
	0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x61, 0x78,
	0x5f, 0x69, 0x64, 0x18, 0x10, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x6e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x61, 0x78, 0x49, 0x64, 0x12, 0x3b, 0x0a, 0x0c,
	0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x11, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x2e, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x6e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x6f, 0x70,
	0x69, 0x63, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x12, 0x20, 0x03, 0x28, 0x03, 0x52, 0x08, 0x74, 0x6f,
	0x70, 0x69, 0x63, 0x49, 0x64, 0x73, 0x32, 0x99, 0x0b, 0x0a, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x12,
	0x3a, 0x0a, 0x05, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x5f, 0x67, 0x65, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x61,
	0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x0a, 0x54,
	0x6f, 0x70, 0x69, 0x63, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x74,
	0x61, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x0a,
	0x54, 0x6f, 0x70, 0x69, 0x63, 0x4d, 0x61, 0x78, 0x49, 0x64, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65,
	0x74, 0x61, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x22, 0x00, 0x12, 0x3c, 0x0a,
	0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x5f, 0x67, 0x65, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x61,
	0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x0c, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4d, 0x61, 0x78, 0x49, 0x64, 0x12, 0x16, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d,
	0x65, 0x74, 0x61, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x22, 0x00, 0x12, 0x44,
	0x0a, 0x0f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x79, 0x50, 0x61, 0x67, 0x69, 0x6e,
	0x67, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65,
	0x74, 0x61, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x16, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x4d, 0x65, 0x74, 0x61, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x22, 0x00, 0x12,
	0x41, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x41, 0x6c, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f,
	0x67, 0x65, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x74, 0x61,
	0x22, 0x00, 0x12, 0x3e, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x61, 0x78, 0x49, 0x64, 0x12,
	0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f,
	0x67, 0x65, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x74, 0x61,
	0x22, 0x00, 0x12, 0x3c, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x16, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x4d, 0x65, 0x74, 0x61, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65,
	0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x22, 0x00,
	0x12, 0x3f, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x47, 0x65, 0x74, 0x12, 0x16,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67,
	0x65, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x22,
	0x00, 0x12, 0x42, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d,
	0x65, 0x74, 0x61, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x12, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x16, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d,
	0x65, 0x74, 0x61, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x22, 0x00, 0x12, 0x44,
	0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x47, 0x65,
	0x74, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65,
	0x74, 0x61, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0b, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x4d, 0x61,
	0x78, 0x49, 0x64, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x1a, 0x17, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x4d, 0x65, 0x74, 0x61, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x0d, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x46, 0x69, 0x6e, 0x64, 0x4f, 0x6e, 0x65, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f,
	0x67, 0x65, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x1a,
	0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x15, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x42, 0x79, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x1a, 0x17, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x4d, 0x65, 0x74, 0x61, 0x22, 0x00, 0x12, 0x59, 0x0a, 0x24, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x55,
	0x73, 0x69, 0x6e, 0x67, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67,
	0x65, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x22,
	0x00, 0x12, 0x39, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x74,
	0x61, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x22, 0x00, 0x12, 0x53, 0x0a, 0x1e,
	0x46, 0x69, 0x6c, 0x65, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x53, 0x75, 0x62, 0x73, 0x12, 0x16,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67,
	0x65, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x22,
	0x00, 0x12, 0x3f, 0x0a, 0x0a, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12,
	0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f,
	0x67, 0x65, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x74, 0x61,
	0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x67, 0x65, 0x6e,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_meta_proto_rawDescOnce sync.Once
	file_meta_proto_rawDescData = file_meta_proto_rawDesc
)

func file_meta_proto_rawDescGZIP() []byte {
	file_meta_proto_rawDescOnce.Do(func() {
		file_meta_proto_rawDescData = protoimpl.X.CompressGZIP(file_meta_proto_rawDescData)
	})
	return file_meta_proto_rawDescData
}

var file_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_meta_proto_goTypes = []interface{}{
	(*RequestMeta)(nil),  // 0: proto_gen.RequestMeta
	(*ResponseMeta)(nil), // 1: proto_gen.ResponseMeta
	(*Header)(nil),       // 2: proto_gen.Header
	(*Paging)(nil),       // 3: proto_gen.Paging
	(*File)(nil),         // 4: proto_gen.File
	(*Profile)(nil),      // 5: proto_gen.Profile
	(*Topic)(nil),        // 6: proto_gen.Topic
	(*Message)(nil),      // 7: proto_gen.Message
	(*User)(nil),         // 8: proto_gen.User
	(*Notification)(nil), // 9: proto_gen.Notification
	(*Result)(nil),       // 10: proto_gen.Result
}
var file_meta_proto_depIdxs = []int32{
	2,  // 0: proto_gen.RequestMeta.header:type_name -> proto_gen.Header
	3,  // 1: proto_gen.RequestMeta.paging:type_name -> proto_gen.Paging
	4,  // 2: proto_gen.RequestMeta.file:type_name -> proto_gen.File
	5,  // 3: proto_gen.RequestMeta.profile:type_name -> proto_gen.Profile
	2,  // 4: proto_gen.ResponseMeta.header:type_name -> proto_gen.Header
	6,  // 5: proto_gen.ResponseMeta.topic:type_name -> proto_gen.Topic
	7,  // 6: proto_gen.ResponseMeta.messages:type_name -> proto_gen.Message
	8,  // 7: proto_gen.ResponseMeta.users:type_name -> proto_gen.User
	5,  // 8: proto_gen.ResponseMeta.profiles:type_name -> proto_gen.Profile
	5,  // 9: proto_gen.ResponseMeta.profile:type_name -> proto_gen.Profile
	4,  // 10: proto_gen.ResponseMeta.file:type_name -> proto_gen.File
	9,  // 11: proto_gen.ResponseMeta.notifications:type_name -> proto_gen.Notification
	10, // 12: proto_gen.ResponseMeta.result:type_name -> proto_gen.Result
	9,  // 13: proto_gen.ResponseMeta.notification:type_name -> proto_gen.Notification
	0,  // 14: proto_gen.Meta.Topic:input_type -> proto_gen.RequestMeta
	0,  // 15: proto_gen.Meta.TopicCount:input_type -> proto_gen.RequestMeta
	0,  // 16: proto_gen.Meta.TopicMaxId:input_type -> proto_gen.RequestMeta
	0,  // 17: proto_gen.Meta.Message:input_type -> proto_gen.RequestMeta
	0,  // 18: proto_gen.Meta.MessageMaxId:input_type -> proto_gen.RequestMeta
	0,  // 19: proto_gen.Meta.MessageByPaging:input_type -> proto_gen.RequestMeta
	0,  // 20: proto_gen.Meta.User:input_type -> proto_gen.RequestMeta
	0,  // 21: proto_gen.Meta.UserAllCount:input_type -> proto_gen.RequestMeta
	0,  // 22: proto_gen.Meta.UserMaxId:input_type -> proto_gen.RequestMeta
	0,  // 23: proto_gen.Meta.Profile:input_type -> proto_gen.RequestMeta
	0,  // 24: proto_gen.Meta.ProfileGet:input_type -> proto_gen.RequestMeta
	0,  // 25: proto_gen.Meta.ProfileUpdate:input_type -> proto_gen.RequestMeta
	0,  // 26: proto_gen.Meta.ProfileImageUpdate:input_type -> proto_gen.RequestMeta
	0,  // 27: proto_gen.Meta.ProfileImageGet:input_type -> proto_gen.RequestMeta
	0,  // 28: proto_gen.Meta.NotifyMaxId:input_type -> proto_gen.RequestMeta
	0,  // 29: proto_gen.Meta.NotifyFindOne:input_type -> proto_gen.RequestMeta
	0,  // 30: proto_gen.Meta.NotifyFindAllByUserId:input_type -> proto_gen.RequestMeta
	0,  // 31: proto_gen.Meta.NotifyFindAllByUserIdUsingPagination:input_type -> proto_gen.RequestMeta
	0,  // 32: proto_gen.Meta.File:input_type -> proto_gen.RequestMeta
	0,  // 33: proto_gen.Meta.FileDownloadsValidateTopicSubs:input_type -> proto_gen.RequestMeta
	0,  // 34: proto_gen.Meta.FileDelete:input_type -> proto_gen.RequestMeta
	1,  // 35: proto_gen.Meta.Topic:output_type -> proto_gen.ResponseMeta
	1,  // 36: proto_gen.Meta.TopicCount:output_type -> proto_gen.ResponseMeta
	1,  // 37: proto_gen.Meta.TopicMaxId:output_type -> proto_gen.ResponseMeta
	1,  // 38: proto_gen.Meta.Message:output_type -> proto_gen.ResponseMeta
	1,  // 39: proto_gen.Meta.MessageMaxId:output_type -> proto_gen.ResponseMeta
	1,  // 40: proto_gen.Meta.MessageByPaging:output_type -> proto_gen.ResponseMeta
	1,  // 41: proto_gen.Meta.User:output_type -> proto_gen.ResponseMeta
	1,  // 42: proto_gen.Meta.UserAllCount:output_type -> proto_gen.ResponseMeta
	1,  // 43: proto_gen.Meta.UserMaxId:output_type -> proto_gen.ResponseMeta
	1,  // 44: proto_gen.Meta.Profile:output_type -> proto_gen.ResponseMeta
	1,  // 45: proto_gen.Meta.ProfileGet:output_type -> proto_gen.ResponseMeta
	1,  // 46: proto_gen.Meta.ProfileUpdate:output_type -> proto_gen.ResponseMeta
	1,  // 47: proto_gen.Meta.ProfileImageUpdate:output_type -> proto_gen.ResponseMeta
	1,  // 48: proto_gen.Meta.ProfileImageGet:output_type -> proto_gen.ResponseMeta
	1,  // 49: proto_gen.Meta.NotifyMaxId:output_type -> proto_gen.ResponseMeta
	1,  // 50: proto_gen.Meta.NotifyFindOne:output_type -> proto_gen.ResponseMeta
	1,  // 51: proto_gen.Meta.NotifyFindAllByUserId:output_type -> proto_gen.ResponseMeta
	1,  // 52: proto_gen.Meta.NotifyFindAllByUserIdUsingPagination:output_type -> proto_gen.ResponseMeta
	1,  // 53: proto_gen.Meta.File:output_type -> proto_gen.ResponseMeta
	1,  // 54: proto_gen.Meta.FileDownloadsValidateTopicSubs:output_type -> proto_gen.ResponseMeta
	1,  // 55: proto_gen.Meta.FileDelete:output_type -> proto_gen.ResponseMeta
	35, // [35:56] is the sub-list for method output_type
	14, // [14:35] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_meta_proto_init() }
func file_meta_proto_init() {
	if File_meta_proto != nil {
		return
	}
	file_model_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_meta_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meta_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_meta_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_meta_proto_goTypes,
		DependencyIndexes: file_meta_proto_depIdxs,
		MessageInfos:      file_meta_proto_msgTypes,
	}.Build()
	File_meta_proto = out.File
	file_meta_proto_rawDesc = nil
	file_meta_proto_goTypes = nil
	file_meta_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MetaClient is the client API for Meta service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MetaClient interface {
	Topic(ctx context.Context, in *RequestMeta, opts ...grpc.CallOption) (*ResponseMeta, error)
	TopicCount(ctx context.Context, in *RequestMeta, opts ...grpc.CallOption) (*ResponseMeta, error)
	TopicMaxId(ctx context.Context, in *RequestMeta, opts ...grpc.CallOption) (*ResponseMeta, error)
	Message(ctx context.Context, in *RequestMeta, opts ...grpc.CallOption) (*ResponseMeta, error)
	MessageMaxId(ctx context.Context, in *RequestMeta, opts ...grpc.CallOption) (*ResponseMeta, error)
	MessageByPaging(ctx context.Context, in *RequestMeta, opts ...grpc.CallOption) (*ResponseMeta, error)
	User(ctx context.Context, in *RequestMeta, opts ...grpc.CallOption) (*ResponseMeta, error)
	UserAllCount(ctx context.Context, in *RequestMeta, opts ...grpc.CallOption) (*ResponseMeta, error)
	UserMaxId(ctx context.Context, in *RequestMeta, opts ...grpc.CallOption) (*ResponseMeta, error)
	Profile(ctx context.Context, in *RequestMeta, opts ...grpc.CallOption) (*ResponseMeta, error)
	ProfileGet(ctx context.Context, in *RequestMeta, opts ...grpc.CallOption) (*ResponseMeta, error)
	ProfileUpdate(ctx context.Context, in *RequestMeta, opts ...grpc.CallOption) (*ResponseMeta, error)
	ProfileImageUpdate(ctx context.Context, in *RequestMeta, opts ...grpc.CallOption) (*ResponseMeta, error)
	ProfileImageGet(ctx context.Context, in *RequestMeta, opts ...grpc.CallOption) (*ResponseMeta, error)
	NotifyMaxId(ctx context.Context, in *RequestMeta, opts ...grpc.CallOption) (*ResponseMeta, error)
	NotifyFindOne(ctx context.Context, in *RequestMeta, opts ...grpc.CallOption) (*ResponseMeta, error)
	NotifyFindAllByUserId(ctx context.Context, in *RequestMeta, opts ...grpc.CallOption) (*ResponseMeta, error)
	NotifyFindAllByUserIdUsingPagination(ctx context.Context, in *RequestMeta, opts ...grpc.CallOption) (*ResponseMeta, error)
	File(ctx context.Context, in *RequestMeta, opts ...grpc.CallOption) (*ResponseMeta, error)
	FileDownloadsValidateTopicSubs(ctx context.Context, in *RequestMeta, opts ...grpc.CallOption) (*ResponseMeta, error)
	FileDelete(ctx context.Context, in *RequestMeta, opts ...grpc.CallOption) (*ResponseMeta, error)
}

type metaClient struct {
	cc grpc.ClientConnInterface
}

func NewMetaClient(cc grpc.ClientConnInterface) MetaClient {
	return &metaClient{cc}
}

func (c *metaClient) Topic(ctx context.Context, in *RequestMeta, opts ...grpc.CallOption) (*ResponseMeta, error) {
	out := new(ResponseMeta)
	err := c.cc.Invoke(ctx, "/proto_gen.Meta/Topic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaClient) TopicCount(ctx context.Context, in *RequestMeta, opts ...grpc.CallOption) (*ResponseMeta, error) {
	out := new(ResponseMeta)
	err := c.cc.Invoke(ctx, "/proto_gen.Meta/TopicCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaClient) TopicMaxId(ctx context.Context, in *RequestMeta, opts ...grpc.CallOption) (*ResponseMeta, error) {
	out := new(ResponseMeta)
	err := c.cc.Invoke(ctx, "/proto_gen.Meta/TopicMaxId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaClient) Message(ctx context.Context, in *RequestMeta, opts ...grpc.CallOption) (*ResponseMeta, error) {
	out := new(ResponseMeta)
	err := c.cc.Invoke(ctx, "/proto_gen.Meta/Message", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaClient) MessageMaxId(ctx context.Context, in *RequestMeta, opts ...grpc.CallOption) (*ResponseMeta, error) {
	out := new(ResponseMeta)
	err := c.cc.Invoke(ctx, "/proto_gen.Meta/MessageMaxId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaClient) MessageByPaging(ctx context.Context, in *RequestMeta, opts ...grpc.CallOption) (*ResponseMeta, error) {
	out := new(ResponseMeta)
	err := c.cc.Invoke(ctx, "/proto_gen.Meta/MessageByPaging", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaClient) User(ctx context.Context, in *RequestMeta, opts ...grpc.CallOption) (*ResponseMeta, error) {
	out := new(ResponseMeta)
	err := c.cc.Invoke(ctx, "/proto_gen.Meta/User", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaClient) UserAllCount(ctx context.Context, in *RequestMeta, opts ...grpc.CallOption) (*ResponseMeta, error) {
	out := new(ResponseMeta)
	err := c.cc.Invoke(ctx, "/proto_gen.Meta/UserAllCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaClient) UserMaxId(ctx context.Context, in *RequestMeta, opts ...grpc.CallOption) (*ResponseMeta, error) {
	out := new(ResponseMeta)
	err := c.cc.Invoke(ctx, "/proto_gen.Meta/UserMaxId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaClient) Profile(ctx context.Context, in *RequestMeta, opts ...grpc.CallOption) (*ResponseMeta, error) {
	out := new(ResponseMeta)
	err := c.cc.Invoke(ctx, "/proto_gen.Meta/Profile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaClient) ProfileGet(ctx context.Context, in *RequestMeta, opts ...grpc.CallOption) (*ResponseMeta, error) {
	out := new(ResponseMeta)
	err := c.cc.Invoke(ctx, "/proto_gen.Meta/ProfileGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaClient) ProfileUpdate(ctx context.Context, in *RequestMeta, opts ...grpc.CallOption) (*ResponseMeta, error) {
	out := new(ResponseMeta)
	err := c.cc.Invoke(ctx, "/proto_gen.Meta/ProfileUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaClient) ProfileImageUpdate(ctx context.Context, in *RequestMeta, opts ...grpc.CallOption) (*ResponseMeta, error) {
	out := new(ResponseMeta)
	err := c.cc.Invoke(ctx, "/proto_gen.Meta/ProfileImageUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaClient) ProfileImageGet(ctx context.Context, in *RequestMeta, opts ...grpc.CallOption) (*ResponseMeta, error) {
	out := new(ResponseMeta)
	err := c.cc.Invoke(ctx, "/proto_gen.Meta/ProfileImageGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaClient) NotifyMaxId(ctx context.Context, in *RequestMeta, opts ...grpc.CallOption) (*ResponseMeta, error) {
	out := new(ResponseMeta)
	err := c.cc.Invoke(ctx, "/proto_gen.Meta/NotifyMaxId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaClient) NotifyFindOne(ctx context.Context, in *RequestMeta, opts ...grpc.CallOption) (*ResponseMeta, error) {
	out := new(ResponseMeta)
	err := c.cc.Invoke(ctx, "/proto_gen.Meta/NotifyFindOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaClient) NotifyFindAllByUserId(ctx context.Context, in *RequestMeta, opts ...grpc.CallOption) (*ResponseMeta, error) {
	out := new(ResponseMeta)
	err := c.cc.Invoke(ctx, "/proto_gen.Meta/NotifyFindAllByUserId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaClient) NotifyFindAllByUserIdUsingPagination(ctx context.Context, in *RequestMeta, opts ...grpc.CallOption) (*ResponseMeta, error) {
	out := new(ResponseMeta)
	err := c.cc.Invoke(ctx, "/proto_gen.Meta/NotifyFindAllByUserIdUsingPagination", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaClient) File(ctx context.Context, in *RequestMeta, opts ...grpc.CallOption) (*ResponseMeta, error) {
	out := new(ResponseMeta)
	err := c.cc.Invoke(ctx, "/proto_gen.Meta/File", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaClient) FileDownloadsValidateTopicSubs(ctx context.Context, in *RequestMeta, opts ...grpc.CallOption) (*ResponseMeta, error) {
	out := new(ResponseMeta)
	err := c.cc.Invoke(ctx, "/proto_gen.Meta/FileDownloadsValidateTopicSubs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaClient) FileDelete(ctx context.Context, in *RequestMeta, opts ...grpc.CallOption) (*ResponseMeta, error) {
	out := new(ResponseMeta)
	err := c.cc.Invoke(ctx, "/proto_gen.Meta/FileDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetaServer is the server API for Meta service.
type MetaServer interface {
	Topic(context.Context, *RequestMeta) (*ResponseMeta, error)
	TopicCount(context.Context, *RequestMeta) (*ResponseMeta, error)
	TopicMaxId(context.Context, *RequestMeta) (*ResponseMeta, error)
	Message(context.Context, *RequestMeta) (*ResponseMeta, error)
	MessageMaxId(context.Context, *RequestMeta) (*ResponseMeta, error)
	MessageByPaging(context.Context, *RequestMeta) (*ResponseMeta, error)
	User(context.Context, *RequestMeta) (*ResponseMeta, error)
	UserAllCount(context.Context, *RequestMeta) (*ResponseMeta, error)
	UserMaxId(context.Context, *RequestMeta) (*ResponseMeta, error)
	Profile(context.Context, *RequestMeta) (*ResponseMeta, error)
	ProfileGet(context.Context, *RequestMeta) (*ResponseMeta, error)
	ProfileUpdate(context.Context, *RequestMeta) (*ResponseMeta, error)
	ProfileImageUpdate(context.Context, *RequestMeta) (*ResponseMeta, error)
	ProfileImageGet(context.Context, *RequestMeta) (*ResponseMeta, error)
	NotifyMaxId(context.Context, *RequestMeta) (*ResponseMeta, error)
	NotifyFindOne(context.Context, *RequestMeta) (*ResponseMeta, error)
	NotifyFindAllByUserId(context.Context, *RequestMeta) (*ResponseMeta, error)
	NotifyFindAllByUserIdUsingPagination(context.Context, *RequestMeta) (*ResponseMeta, error)
	File(context.Context, *RequestMeta) (*ResponseMeta, error)
	FileDownloadsValidateTopicSubs(context.Context, *RequestMeta) (*ResponseMeta, error)
	FileDelete(context.Context, *RequestMeta) (*ResponseMeta, error)
}

// UnimplementedMetaServer can be embedded to have forward compatible implementations.
type UnimplementedMetaServer struct {
}

func (*UnimplementedMetaServer) Topic(context.Context, *RequestMeta) (*ResponseMeta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Topic not implemented")
}
func (*UnimplementedMetaServer) TopicCount(context.Context, *RequestMeta) (*ResponseMeta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TopicCount not implemented")
}
func (*UnimplementedMetaServer) TopicMaxId(context.Context, *RequestMeta) (*ResponseMeta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TopicMaxId not implemented")
}
func (*UnimplementedMetaServer) Message(context.Context, *RequestMeta) (*ResponseMeta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Message not implemented")
}
func (*UnimplementedMetaServer) MessageMaxId(context.Context, *RequestMeta) (*ResponseMeta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MessageMaxId not implemented")
}
func (*UnimplementedMetaServer) MessageByPaging(context.Context, *RequestMeta) (*ResponseMeta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MessageByPaging not implemented")
}
func (*UnimplementedMetaServer) User(context.Context, *RequestMeta) (*ResponseMeta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User not implemented")
}
func (*UnimplementedMetaServer) UserAllCount(context.Context, *RequestMeta) (*ResponseMeta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserAllCount not implemented")
}
func (*UnimplementedMetaServer) UserMaxId(context.Context, *RequestMeta) (*ResponseMeta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserMaxId not implemented")
}
func (*UnimplementedMetaServer) Profile(context.Context, *RequestMeta) (*ResponseMeta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Profile not implemented")
}
func (*UnimplementedMetaServer) ProfileGet(context.Context, *RequestMeta) (*ResponseMeta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProfileGet not implemented")
}
func (*UnimplementedMetaServer) ProfileUpdate(context.Context, *RequestMeta) (*ResponseMeta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProfileUpdate not implemented")
}
func (*UnimplementedMetaServer) ProfileImageUpdate(context.Context, *RequestMeta) (*ResponseMeta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProfileImageUpdate not implemented")
}
func (*UnimplementedMetaServer) ProfileImageGet(context.Context, *RequestMeta) (*ResponseMeta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProfileImageGet not implemented")
}
func (*UnimplementedMetaServer) NotifyMaxId(context.Context, *RequestMeta) (*ResponseMeta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyMaxId not implemented")
}
func (*UnimplementedMetaServer) NotifyFindOne(context.Context, *RequestMeta) (*ResponseMeta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyFindOne not implemented")
}
func (*UnimplementedMetaServer) NotifyFindAllByUserId(context.Context, *RequestMeta) (*ResponseMeta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyFindAllByUserId not implemented")
}
func (*UnimplementedMetaServer) NotifyFindAllByUserIdUsingPagination(context.Context, *RequestMeta) (*ResponseMeta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyFindAllByUserIdUsingPagination not implemented")
}
func (*UnimplementedMetaServer) File(context.Context, *RequestMeta) (*ResponseMeta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method File not implemented")
}
func (*UnimplementedMetaServer) FileDownloadsValidateTopicSubs(context.Context, *RequestMeta) (*ResponseMeta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FileDownloadsValidateTopicSubs not implemented")
}
func (*UnimplementedMetaServer) FileDelete(context.Context, *RequestMeta) (*ResponseMeta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FileDelete not implemented")
}

func RegisterMetaServer(s *grpc.Server, srv MetaServer) {
	s.RegisterService(&_Meta_serviceDesc, srv)
}

func _Meta_Topic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMeta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServer).Topic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_gen.Meta/Topic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServer).Topic(ctx, req.(*RequestMeta))
	}
	return interceptor(ctx, in, info, handler)
}

func _Meta_TopicCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMeta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServer).TopicCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_gen.Meta/TopicCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServer).TopicCount(ctx, req.(*RequestMeta))
	}
	return interceptor(ctx, in, info, handler)
}

func _Meta_TopicMaxId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMeta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServer).TopicMaxId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_gen.Meta/TopicMaxId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServer).TopicMaxId(ctx, req.(*RequestMeta))
	}
	return interceptor(ctx, in, info, handler)
}

func _Meta_Message_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMeta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServer).Message(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_gen.Meta/Message",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServer).Message(ctx, req.(*RequestMeta))
	}
	return interceptor(ctx, in, info, handler)
}

func _Meta_MessageMaxId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMeta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServer).MessageMaxId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_gen.Meta/MessageMaxId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServer).MessageMaxId(ctx, req.(*RequestMeta))
	}
	return interceptor(ctx, in, info, handler)
}

func _Meta_MessageByPaging_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMeta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServer).MessageByPaging(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_gen.Meta/MessageByPaging",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServer).MessageByPaging(ctx, req.(*RequestMeta))
	}
	return interceptor(ctx, in, info, handler)
}

func _Meta_User_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMeta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServer).User(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_gen.Meta/User",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServer).User(ctx, req.(*RequestMeta))
	}
	return interceptor(ctx, in, info, handler)
}

func _Meta_UserAllCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMeta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServer).UserAllCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_gen.Meta/UserAllCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServer).UserAllCount(ctx, req.(*RequestMeta))
	}
	return interceptor(ctx, in, info, handler)
}

func _Meta_UserMaxId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMeta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServer).UserMaxId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_gen.Meta/UserMaxId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServer).UserMaxId(ctx, req.(*RequestMeta))
	}
	return interceptor(ctx, in, info, handler)
}

func _Meta_Profile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMeta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServer).Profile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_gen.Meta/Profile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServer).Profile(ctx, req.(*RequestMeta))
	}
	return interceptor(ctx, in, info, handler)
}

func _Meta_ProfileGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMeta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServer).ProfileGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_gen.Meta/ProfileGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServer).ProfileGet(ctx, req.(*RequestMeta))
	}
	return interceptor(ctx, in, info, handler)
}

func _Meta_ProfileUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMeta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServer).ProfileUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_gen.Meta/ProfileUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServer).ProfileUpdate(ctx, req.(*RequestMeta))
	}
	return interceptor(ctx, in, info, handler)
}

func _Meta_ProfileImageUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMeta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServer).ProfileImageUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_gen.Meta/ProfileImageUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServer).ProfileImageUpdate(ctx, req.(*RequestMeta))
	}
	return interceptor(ctx, in, info, handler)
}

func _Meta_ProfileImageGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMeta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServer).ProfileImageGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_gen.Meta/ProfileImageGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServer).ProfileImageGet(ctx, req.(*RequestMeta))
	}
	return interceptor(ctx, in, info, handler)
}

func _Meta_NotifyMaxId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMeta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServer).NotifyMaxId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_gen.Meta/NotifyMaxId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServer).NotifyMaxId(ctx, req.(*RequestMeta))
	}
	return interceptor(ctx, in, info, handler)
}

func _Meta_NotifyFindOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMeta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServer).NotifyFindOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_gen.Meta/NotifyFindOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServer).NotifyFindOne(ctx, req.(*RequestMeta))
	}
	return interceptor(ctx, in, info, handler)
}

func _Meta_NotifyFindAllByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMeta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServer).NotifyFindAllByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_gen.Meta/NotifyFindAllByUserId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServer).NotifyFindAllByUserId(ctx, req.(*RequestMeta))
	}
	return interceptor(ctx, in, info, handler)
}

func _Meta_NotifyFindAllByUserIdUsingPagination_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMeta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServer).NotifyFindAllByUserIdUsingPagination(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_gen.Meta/NotifyFindAllByUserIdUsingPagination",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServer).NotifyFindAllByUserIdUsingPagination(ctx, req.(*RequestMeta))
	}
	return interceptor(ctx, in, info, handler)
}

func _Meta_File_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMeta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServer).File(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_gen.Meta/File",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServer).File(ctx, req.(*RequestMeta))
	}
	return interceptor(ctx, in, info, handler)
}

func _Meta_FileDownloadsValidateTopicSubs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMeta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServer).FileDownloadsValidateTopicSubs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_gen.Meta/FileDownloadsValidateTopicSubs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServer).FileDownloadsValidateTopicSubs(ctx, req.(*RequestMeta))
	}
	return interceptor(ctx, in, info, handler)
}

func _Meta_FileDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMeta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServer).FileDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_gen.Meta/FileDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServer).FileDelete(ctx, req.(*RequestMeta))
	}
	return interceptor(ctx, in, info, handler)
}

var _Meta_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto_gen.Meta",
	HandlerType: (*MetaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Topic",
			Handler:    _Meta_Topic_Handler,
		},
		{
			MethodName: "TopicCount",
			Handler:    _Meta_TopicCount_Handler,
		},
		{
			MethodName: "TopicMaxId",
			Handler:    _Meta_TopicMaxId_Handler,
		},
		{
			MethodName: "Message",
			Handler:    _Meta_Message_Handler,
		},
		{
			MethodName: "MessageMaxId",
			Handler:    _Meta_MessageMaxId_Handler,
		},
		{
			MethodName: "MessageByPaging",
			Handler:    _Meta_MessageByPaging_Handler,
		},
		{
			MethodName: "User",
			Handler:    _Meta_User_Handler,
		},
		{
			MethodName: "UserAllCount",
			Handler:    _Meta_UserAllCount_Handler,
		},
		{
			MethodName: "UserMaxId",
			Handler:    _Meta_UserMaxId_Handler,
		},
		{
			MethodName: "Profile",
			Handler:    _Meta_Profile_Handler,
		},
		{
			MethodName: "ProfileGet",
			Handler:    _Meta_ProfileGet_Handler,
		},
		{
			MethodName: "ProfileUpdate",
			Handler:    _Meta_ProfileUpdate_Handler,
		},
		{
			MethodName: "ProfileImageUpdate",
			Handler:    _Meta_ProfileImageUpdate_Handler,
		},
		{
			MethodName: "ProfileImageGet",
			Handler:    _Meta_ProfileImageGet_Handler,
		},
		{
			MethodName: "NotifyMaxId",
			Handler:    _Meta_NotifyMaxId_Handler,
		},
		{
			MethodName: "NotifyFindOne",
			Handler:    _Meta_NotifyFindOne_Handler,
		},
		{
			MethodName: "NotifyFindAllByUserId",
			Handler:    _Meta_NotifyFindAllByUserId_Handler,
		},
		{
			MethodName: "NotifyFindAllByUserIdUsingPagination",
			Handler:    _Meta_NotifyFindAllByUserIdUsingPagination_Handler,
		},
		{
			MethodName: "File",
			Handler:    _Meta_File_Handler,
		},
		{
			MethodName: "FileDownloadsValidateTopicSubs",
			Handler:    _Meta_FileDownloadsValidateTopicSubs_Handler,
		},
		{
			MethodName: "FileDelete",
			Handler:    _Meta_FileDelete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "meta.proto",
}
